name: app_exception
description: Template for Flutter Package project.
version: 0.0.2+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 4-SEP-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.17.12

flutter:
  uses-material-design: true
