name: app_exception
description: Template for Flutter Package project.
version: 0.1.0+2
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.3 <3.0.0" #Dart SDK 7-OCT-2021
  flutter: ">=2.5.2"


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.18.2

flutter:
  uses-material-design: true
