name: app_exception
description: Implements Exception for creating app specific errors
version: 0.0.2+2
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.20.1

flutter:
  uses-material-design: true
