name: app_exception
description: Template for Flutter Package project.
version: 0.1.0+1
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0" #Dart SDK 12-SEP-2021
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.17.12

flutter:
  uses-material-design: true
